// <auto-generated />
using System;
using AgriConnect_St10258400_Erin_PROG7311.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgriConnect_St10258400_Erin_PROG7311.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250514142220_seedingDatatoTables")]
    partial class seedingDatatoTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgriConnect_St10258400_Erin_PROG7311.Models.EmployeeModel", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeId"));

                    b.Property<string>("employeeEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("employeeLastName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("employeeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeePasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employeeId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            employeeId = 1,
                            employeeEmail = "e.s@gmail.com",
                            employeeFirstName = "Erin",
                            employeeLastName = "Steenveld",
                            employeeNumber = "1234567890",
                            employeePasswordHash = "AQAAAAIAAYagAAAAEAtucICMr/9Qo7oY64ZKjuDNQl4o4IEKTGLnIg2me6gWsT/igV3gX74Rq5fCfXf+tw=="
                        },
                        new
                        {
                            employeeId = 2,
                            employeeEmail = "c.f@gmail.com",
                            employeeFirstName = "Clive",
                            employeeLastName = "Frankland",
                            employeeNumber = "0987654321",
                            employeePasswordHash = "AQAAAAIAAYagAAAAEJsmEhWsXodkJ0v9yjYctFqboVA3gwmODW59YFnf2fXa9Wz2mE1CUJigmXMZZGxfxw=="
                        });
                });

            modelBuilder.Entity("AgriConnect_St10258400_Erin_PROG7311.Models.FarmerModel", b =>
                {
                    b.Property<int>("farmerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("farmerId"));

                    b.Property<string>("farmerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("farmerFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("farmerLastName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("farmerLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("farmerPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("farmerPasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("farmerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("farmerId");

                    b.ToTable("Farmer");

                    b.HasData(
                        new
                        {
                            farmerId = 1,
                            farmerEmail = "j.m@gmail.com",
                            farmerFirstName = "Jack",
                            farmerLastName = "Mcdonald",
                            farmerLocation = "Paarl",
                            farmerPassword = "Pass1234!",
                            farmerPasswordHash = "AQAAAAIAAYagAAAAEANU33h/MGee9PzXT11T3ttuLMaRyucNSwTVig0eSlovR5RbKRsbc7j7GQvsydQjKA==",
                            farmerRole = "Farmer"
                        },
                        new
                        {
                            farmerId = 2,
                            farmerEmail = "p.l@gmail.com",
                            farmerFirstName = "Penny",
                            farmerLastName = "Leaf",
                            farmerLocation = "Cape Town",
                            farmerPassword = "Pass1234!",
                            farmerPasswordHash = "AQAAAAIAAYagAAAAEANU33h/MGee9PzXT11T3ttuLMaRyucNSwTVig0eSlovR5RbKRsbc7j7GQvsydQjKA==",
                            farmerRole = "Farmer"
                        },
                        new
                        {
                            farmerId = 3,
                            farmerEmail = "m.v@gmail.com",
                            farmerFirstName = "Max",
                            farmerLastName = "Verstappen",
                            farmerLocation = "Stenllenbosch",
                            farmerPassword = "Pass1234!",
                            farmerPasswordHash = "AQAAAAIAAYagAAAAEANU33h/MGee9PzXT11T3ttuLMaRyucNSwTVig0eSlovR5RbKRsbc7j7GQvsydQjKA==",
                            farmerRole = "Farmer"
                        },
                        new
                        {
                            farmerId = 4,
                            farmerEmail = "l.b@gmail.com",
                            farmerFirstName = "Lilly",
                            farmerLastName = "Brown",
                            farmerLocation = "Onrus",
                            farmerPassword = "Pass1234!",
                            farmerPasswordHash = "AQAAAAIAAYagAAAAEANU33h/MGee9PzXT11T3ttuLMaRyucNSwTVig0eSlovR5RbKRsbc7j7GQvsydQjKA==",
                            farmerRole = "Farmer"
                        });
                });

            modelBuilder.Entity("AgriConnect_St10258400_Erin_PROG7311.Models.ProductModel", b =>
                {
                    b.Property<int>("productID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productID"));

                    b.Property<int>("farmerId")
                        .HasColumnType("int");

                    b.Property<int>("productCategory")
                        .HasColumnType("int");

                    b.Property<string>("productDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("productionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("productID");

                    b.HasIndex("farmerId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            productID = 1,
                            farmerId = 1,
                            productCategory = 1,
                            productDescription = "Freshly harvested potatoes",
                            productName = "Potatoes",
                            productionDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 2,
                            farmerId = 1,
                            productCategory = 1,
                            productDescription = "Freshly harvested  orange carrorts",
                            productName = "Carrots",
                            productionDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 3,
                            farmerId = 1,
                            productCategory = 1,
                            productDescription = "Freshly harvested baby radish",
                            productName = "Radish",
                            productionDate = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 4,
                            farmerId = 2,
                            productCategory = 5,
                            productDescription = "Whole Free range chickens",
                            productName = "Chicken",
                            productionDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 5,
                            farmerId = 2,
                            productCategory = 7,
                            productDescription = "Free range eggs",
                            productName = "Brown Eggs",
                            productionDate = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 6,
                            farmerId = 3,
                            productCategory = 0,
                            productDescription = "Big red gala apples",
                            productName = "Apples",
                            productionDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 7,
                            farmerId = 3,
                            productCategory = 0,
                            productDescription = "Freshly harvested bananas",
                            productName = "Bananas",
                            productionDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 8,
                            farmerId = 4,
                            productCategory = 0,
                            productDescription = "Freshly harvested grapes",
                            productName = "Grapes",
                            productionDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 9,
                            farmerId = 4,
                            productCategory = 0,
                            productDescription = "Freshly harvested peaches",
                            productName = "Peaches",
                            productionDate = new DateTime(2025, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 10,
                            farmerId = 1,
                            productCategory = 11,
                            productDescription = "large leaf parsely",
                            productName = "Parsely",
                            productionDate = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 11,
                            farmerId = 2,
                            productCategory = 11,
                            productDescription = "Freshly harvested rosemary",
                            productName = "Rosemary",
                            productionDate = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 12,
                            farmerId = 4,
                            productCategory = 11,
                            productDescription = "Freshly harvested thyme",
                            productName = "Thyme",
                            productionDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 13,
                            farmerId = 3,
                            productCategory = 3,
                            productDescription = "Pasurised  cow milk",
                            productName = "Jersey Milk",
                            productionDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 14,
                            farmerId = 4,
                            productCategory = 3,
                            productDescription = "Pasurised goats milk",
                            productName = "Goats Milk",
                            productionDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 15,
                            farmerId = 2,
                            productCategory = 3,
                            productDescription = " Long fermented brie cheese",
                            productName = "Brie Cheese",
                            productionDate = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 16,
                            farmerId = 4,
                            productCategory = 7,
                            productDescription = "White chicken free range eggs",
                            productName = "White eggs free range",
                            productionDate = new DateTime(2025, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 17,
                            farmerId = 2,
                            productCategory = 4,
                            productDescription = "Free range bacon",
                            productName = "Bacon",
                            productionDate = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 18,
                            farmerId = 4,
                            productCategory = 4,
                            productDescription = "Free range beef",
                            productName = "Beef steaks",
                            productionDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 19,
                            farmerId = 3,
                            productCategory = 2,
                            productDescription = "finley ground rye flour",
                            productName = "Rye Flour",
                            productionDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 20,
                            farmerId = 4,
                            productCategory = 2,
                            productDescription = "finley ground wheat flour",
                            productName = "Wheat Flour",
                            productionDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 21,
                            farmerId = 4,
                            productCategory = 2,
                            productDescription = "finley ground oats",
                            productName = "Oats",
                            productionDate = new DateTime(2025, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 22,
                            farmerId = 2,
                            productCategory = 10,
                            productDescription = "Raw pumkin seeds",
                            productName = "Pumkin seeds",
                            productionDate = new DateTime(2025, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            productID = 23,
                            farmerId = 3,
                            productCategory = 10,
                            productDescription = "Raw sunflower seeds",
                            productName = "Sunflower seeds",
                            productionDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AgriConnect_St10258400_Erin_PROG7311.Models.ProductModel", b =>
                {
                    b.HasOne("AgriConnect_St10258400_Erin_PROG7311.Models.FarmerModel", "farmer")
                        .WithMany("FarmerProducts")
                        .HasForeignKey("farmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("farmer");
                });

            modelBuilder.Entity("AgriConnect_St10258400_Erin_PROG7311.Models.FarmerModel", b =>
                {
                    b.Navigation("FarmerProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
