// <auto-generated />
using System;
using AgriConnect_St10258400_Erin_PROG7311.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgriConnect_St10258400_Erin_PROG7311.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250509213523_empoyeeNumFieldAdded")]
    partial class empoyeeNumFieldAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgriConnect_St10258400_Erin_PROG7311.Models.EmployeeModel", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeId"));

                    b.Property<string>("employeeNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("employeeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("employeeId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("AgriConnect_St10258400_Erin_PROG7311.Models.FarmerModel", b =>
                {
                    b.Property<int>("farmerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("farmerId"));

                    b.Property<string>("farmerLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("farmerId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Farmer");
                });

            modelBuilder.Entity("AgriConnect_St10258400_Erin_PROG7311.Models.ProductModel", b =>
                {
                    b.Property<int>("productID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productID"));

                    b.Property<int>("farmerId")
                        .HasColumnType("int");

                    b.Property<int>("productCategory")
                        .HasColumnType("int");

                    b.Property<string>("productDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("productImage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("productionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("productID");

                    b.HasIndex("farmerId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("AgriConnect_St10258400_Erin_PROG7311.Models.UserModel", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("userLastName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("userPasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AgriConnect_St10258400_Erin_PROG7311.Models.EmployeeModel", b =>
                {
                    b.HasOne("AgriConnect_St10258400_Erin_PROG7311.Models.UserModel", "user")
                        .WithOne("Employee")
                        .HasForeignKey("AgriConnect_St10258400_Erin_PROG7311.Models.EmployeeModel", "userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("AgriConnect_St10258400_Erin_PROG7311.Models.FarmerModel", b =>
                {
                    b.HasOne("AgriConnect_St10258400_Erin_PROG7311.Models.UserModel", "user")
                        .WithOne("Farmer")
                        .HasForeignKey("AgriConnect_St10258400_Erin_PROG7311.Models.FarmerModel", "userId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("AgriConnect_St10258400_Erin_PROG7311.Models.ProductModel", b =>
                {
                    b.HasOne("AgriConnect_St10258400_Erin_PROG7311.Models.FarmerModel", "farmer")
                        .WithMany("FarmerProducts")
                        .HasForeignKey("farmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("farmer");
                });

            modelBuilder.Entity("AgriConnect_St10258400_Erin_PROG7311.Models.FarmerModel", b =>
                {
                    b.Navigation("FarmerProducts");
                });

            modelBuilder.Entity("AgriConnect_St10258400_Erin_PROG7311.Models.UserModel", b =>
                {
                    b.Navigation("Employee")
                        .IsRequired();

                    b.Navigation("Farmer")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
